#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_k2

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clone source code
      env: 
        REPO_URL:  https://github.com/lirihw/openwrt2102-16m
        REPO_BRANCH: openwrt-21.02
      run: |
        git clone  https://github.com/lirihw/lienol_openwrt20221028 openwrt
        cd openwrt
        git clone  https://github.com/fw876/helloworld.git package/ssr
        git clone  https://github.com/xiaorouji/openwrt-passwall package/passwall
        git clone  https://github.com/kevin-morgan/luci-theme-argon-dark package/lean/luci-theme-argon-dark
        #git clone -b openwrt-21.02 https://github.com/openwrt/openwrt.git openwrt
        #git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        #git clone  https://github.com/Lienol/openwrt-package.git package/Lienol
        #git clone  https://github.com/jerrykuku/lua-maxminddb.git package/lean/lua-maxminddb
        #git clone  https://github.com/jerrykuku/luci-app-vssr.git package/lean/luci-app-vssr
        #git clone  https://github.com/Leo-Jo-My/luci-app-vssr-plus.git package/lean/luci-vssr-plus-rely
        #git clone  https://github.com/destan19/OpenAppFilter.git package/lean/luci-app-vssr-plus
        
        #git clone  https://github.com/kenzok8/small package/small
        #git clone  https://github.com/rofl0r/microsocks package/microsocks
        #git clone  https://github.com/wltc2005/openwrt-redsocks2 package/redsocks2
        #git clone https://github.com/More-A/openwrt-ssr package/openwrt-ssr
        #git clone https://github.com/kenzok8/openwrt-packages package/kenzok
        #git clone https://github.com/kevin-morgan/luci-theme-argon-dark package/luci-theme-argon-dark
        #echo "src-git ssrp https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
        
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
     
    #- name: Import external feeds - passwall
    #working-directory: ./openwrt
    #run: |
    # git clone https://github.com/xiaorouji/openwrt-passwall.git package/lienol
    #    git clone "your_github_link" package/"your_folder_name"      

    #- name: Import external feeds - JerryKuKu Argon
    #  working-directory: ./openwrt
    #  run: |
    #    git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon-jerrykuku

    - name: Configuration Customization - Build_k2
      env:
       CONFIG_FILE: 'k2.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        #cp mac80211.sh  openwrt/package/kernel/mac80211/files/lib/wifi
        #chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
    - name: Delete packages
      working-directory: ./openwrt
      run: |
        cd bin
        rm -rf packages
        cd  targets/*/*
        rm -rf packages
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
